### ISSUE TITLE
Back button on iPhone document viewer non-responsive on second view

### ISSUE THREAD

**Issue by garrengotthardt** [artsy/energy#119]
![foliodocbug](https://cloud.githubusercontent.com/assets/1863593/11820767/34fe76f6-a334-11e5-886a-385e0ed7e3f1.gif)

- [ ] when clicking a doc on iPhone, the document viewer allows you to view and press the back button the first time, though on the second time viewing a doc the back button becomes unresponsive
- [ ] native apple share button is offscreen/unresponsive on iphone, and unresponsive on ipad - we should hide this button 

cc: @orta

**Comment by orta** [comment]
I think the fix for this is to _not_ have the view controller we present as a subclass of `QLPreviewController` but as a normal `UIViewController` that has the `QLPreviewController`as a child view controller. ChildVCs didn't exist when I built this.

Then we can remove all the crazy navigation bar logic that I wrote for ~iOS 3 or 4. Which I'm willing to bet will have the side-effect of fixing this.

**Comment by garrengotthardt** [comment]
tested and all good 👌
